# Generated by Django 4.0.4 on 2022-05-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('presentacion', models.CharField(choices=[('bolsa', 'bolsa'), ('caja', 'caja'), ('rack', 'rack'), ('tubo', 'tubo')], max_length=25)),
                ('cantidad', models.IntegerField()),
                ('area_de_trabajo', models.CharField(choices=[('cultivo', 'cultivo'), ('síntesis', 'síntesis'), ('molecular', 'molecular'), ('general', 'general')], max_length=25)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('empresa', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('estado_de_agregacion', models.CharField(choices=[('líquido', 'líquido'), ('sólido', 'sólido')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('almacenamiento', models.CharField(choices=[('temperatura ambiente', 'temperatura ambiente'), ('refrigeración', 'refrigeración'), ('congelación', 'congelación'), ('vacío', 'vacío')], max_length=25)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
