# Generated by Django 4.0.4 on 2022-05-18 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivo',
            name='fecha_agregado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
